name: code
description: Snake code editor

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.9-alpha+01

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.1
  eva_icons_flutter: ^2.0.0
  shared_preferences: ^0.5.6+3
  # path_provider: ^1.6.5
  path: ^1.7.0
  permission_handler: ^5.0.0+hotfix.8

dev_dependencies:
  lint: ^1.0.0
  # flutter_test:s

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-SemiBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-Bold.ttf
          weight: 800
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-Black.ttf
          weight: 900
        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
