# This is a basic workflow to help you get started with Actions

name: Flutter analysis

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, dev/*]
  pull_request:
    branches: [master, dev/*]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "analysis"
  analysis:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup Java environment in order to build the Android app.
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1.3.2
        with:
          # The Flutter version to make available on the path
          flutter-version: 1.17.2 # optional
          # The Flutter build release channel
          channel: stable # optional, default is stable

      - name: Flutter doctor
        run: |
          cd $GITHUB_WORKSPACE/org.purplegrahite.code;
          flutter doctor -v;

      - name: Refreshing dependencies
        run: |
          cd $GITHUB_WORKSPACE/org.purplegrahite.code;
          flutter pub get;

      - name: Flutter code formatting check
        run: |
          cd $GITHUB_WORKSPACE/org.purplegrahite.code;
          flutter format --set-exit-if-changed .;

      - name: analyze issues
        run: |
          cd $GITHUB_WORKSPACE/org.purplegrahite.code;
          flutter analyze .;

  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup Java environment in order to build the Android app.
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1.3.2
        with:
          # The Flutter version to make available on the path
          flutter-version: 1.17.2 # optional
          # The Flutter build release channel
          channel: stable # optional, default is stable
      - name: run tests
        run: |
          cd $GITHUB_WORKSPACE/org.purplegrahite.code;
          flutter test;
